-- MySQL Script generated by MySQL Workbench
-- Mon Apr  8 17:40:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_ usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `nome` VARCHAR(70) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  `passeador` TINYINT NOT NULL,
  `telefone1` VARCHAR(11) NOT NULL,
  `telefone2` VARCHAR(11) NULL,
  `telefone3` VARCHAR(11) NULL,
  PRIMARY KEY (`id_ usuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`id_ usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passeio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passeio` (
  `idpasseio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `observacoes` VARCHAR(255) NOT NULL,
  `horario` TIME NOT NULL,
  `valor` INT UNSIGNED NOT NULL,
  `data` DATE NOT NULL,
  `usuario_passeador_id` INT UNSIGNED NULL,
  PRIMARY KEY (`idpasseio`),
  UNIQUE INDEX `idpasseio_UNIQUE` (`idpasseio` ASC) VISIBLE,
  INDEX `fk_Passeio_Usuario1_idx` (`usuario_passeador_id` ASC) VISIBLE,
  CONSTRAINT `fk_Passeio_Usuario1`
    FOREIGN KEY (`usuario_passeador_id`)
    REFERENCES `mydb`.`Usuario` (`id_ usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pet` (
  `idpet` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `idade` INT UNSIGNED NOT NULL,
  `raca` VARCHAR(50) NOT NULL,
  `perfilcomportamental` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) BINARY NOT NULL,
  `id_dono` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idpet`, `id_dono`),
  UNIQUE INDEX `idpet_UNIQUE` (`idpet` ASC) VISIBLE,
  INDEX `id_dono_idx` (`id_dono` ASC) VISIBLE,
  CONSTRAINT `id_dono`
    FOREIGN KEY (`id_dono`)
    REFERENCES `mydb`.`Usuario` (`id_ usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avaliacao` (
  `idAvaliacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nota` INT UNSIGNED NOT NULL,
  `feedback` VARCHAR(255) NOT NULL,
  `usuario_passeador_id` INT UNSIGNED NOT NULL,
  `usuario_dono_id` INT UNSIGNED NOT NULL,
  `Passeio_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAvaliacao`),
  UNIQUE INDEX `idAvaliacao_UNIQUE` (`idAvaliacao` ASC) VISIBLE,
  INDEX `fk_Avaliacao_Usuario1_idx` (`usuario_passeador_id` ASC) VISIBLE,
  INDEX `fk_Avaliacao_Usuario2_idx` (`usuario_dono_id` ASC) VISIBLE,
  INDEX `fk_Avaliacao_Passeio1_idx` (`Passeio_id` ASC) VISIBLE,
  CONSTRAINT `fk_Avaliacao_Usuario1`
    FOREIGN KEY (`usuario_passeador_id`)
    REFERENCES `mydb`.`Usuario` (`id_ usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Usuario2`
    FOREIGN KEY (`usuario_dono_id`)
    REFERENCES `mydb`.`Usuario` (`id_ usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Passeio1`
    FOREIGN KEY (`Passeio_id`)
    REFERENCES `mydb`.`Passeio` (`idpasseio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vacina` (
  `idvacina` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`idvacina`),
  UNIQUE INDEX `idvacina_UNIQUE` (`idvacina` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doenca` (
  `iddoenca` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(70) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`iddoenca`),
  UNIQUE INDEX `iddoenca_UNIQUE` (`iddoenca` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mensagem` (
  `idmensagem` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mensagem` VARCHAR(255) NOT NULL,
  `data` DATE NOT NULL,
  `idusuarioremetente` INT UNSIGNED NOT NULL,
  `idusuariodestinatario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idmensagem`),
  UNIQUE INDEX `idmensagem_UNIQUE` (`idmensagem` ASC) VISIBLE,
  INDEX `fk_Mensagem_Usuario1_idx` (`idusuarioremetente` ASC) VISIBLE,
  INDEX `fk_Mensagem_Usuario2_idx` (`idusuariodestinatario` ASC) VISIBLE,
  CONSTRAINT `fk_Mensagem_Usuario1`
    FOREIGN KEY (`idusuarioremetente`)
    REFERENCES `mydb`.`Usuario` (`id_ usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensagem_Usuario2`
    FOREIGN KEY (`idusuariodestinatario`)
    REFERENCES `mydb`.`Usuario` (`id_ usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passeio_pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passeio_pet` (
  `Passeio_idpasseio` INT UNSIGNED NOT NULL,
  `Pet_idpet` INT UNSIGNED NOT NULL,
  INDEX `fk_Passeio_pet_Pet1_idx` (`Pet_idpet` ASC) VISIBLE,
  PRIMARY KEY (`Passeio_idpasseio`, `Pet_idpet`),
  CONSTRAINT `fk_Passeio_pet_Passeio1`
    FOREIGN KEY (`Passeio_idpasseio`)
    REFERENCES `mydb`.`Passeio` (`idpasseio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Passeio_pet_Pet1`
    FOREIGN KEY (`Pet_idpet`)
    REFERENCES `mydb`.`Pet` (`idpet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pet_has_doenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pet_has_doenca` (
  `Doenca_iddoenca` INT UNSIGNED NOT NULL,
  `Pet_idpet` INT UNSIGNED NOT NULL,
  `Pet_id_dono` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Doenca_iddoenca`, `Pet_idpet`, `Pet_id_dono`),
  INDEX `fk_Doenca_has_Pet_Pet1_idx` (`Pet_idpet` ASC, `Pet_id_dono` ASC) VISIBLE,
  INDEX `fk_Doenca_has_Pet_Doenca1_idx` (`Doenca_iddoenca` ASC) VISIBLE,
  CONSTRAINT `fk_Doenca_has_Pet_Doenca1`
    FOREIGN KEY (`Doenca_iddoenca`)
    REFERENCES `mydb`.`Doenca` (`iddoenca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doenca_has_Pet_Pet1`
    FOREIGN KEY (`Pet_idpet` , `Pet_id_dono`)
    REFERENCES `mydb`.`Pet` (`idpet` , `id_dono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pet_has_vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pet_has_vacina` (
  `Vacina_idvacina` INT UNSIGNED NOT NULL,
  `Pet_idpet` INT UNSIGNED NOT NULL,
  `Pet_id_dono` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Vacina_idvacina`, `Pet_idpet`, `Pet_id_dono`),
  INDEX `fk_Vacina_has_Pet_Pet1_idx` (`Pet_idpet` ASC, `Pet_id_dono` ASC) VISIBLE,
  INDEX `fk_Vacina_has_Pet_Vacina1_idx` (`Vacina_idvacina` ASC) VISIBLE,
  CONSTRAINT `fk_Vacina_has_Pet_Vacina1`
    FOREIGN KEY (`Vacina_idvacina`)
    REFERENCES `mydb`.`Vacina` (`idvacina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vacina_has_Pet_Pet1`
    FOREIGN KEY (`Pet_idpet` , `Pet_id_dono`)
    REFERENCES `mydb`.`Pet` (`idpet` , `id_dono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
